## 판다스 기초

### 판다스 패키지 로드

import pandas as pd

In [6]:
import pandas as pd
import numpy as np

#### 핵심 자료구조
- `Series` 와 `DataFrame`

#### Series
> 1차원 데이터를 표현하는 자료구조. **인덱스**가 붙어있는 한줄짜리 데이터. 1차원 배열과 흡사

In [7]:
np_scores = np.array([85,90,95,80])
np_scores

array([85, 90, 95, 80])

In [13]:
scores = pd.Series([85,90,95,80])
scores

0    85
1    90
2    95
3    80
dtype: int64

In [12]:
scores[0]

np.int64(85)

- Series 작성시 인덱스를 직접 커스터마이징 할 수 있음

In [14]:
scores = pd.Series(
    [85,90,95,80],
    index=['홍길동','이영희','김철수','박민수']
    )

scores

홍길동    85
이영희    90
김철수    95
박민수    80
dtype: int64

In [ ]:
# 기존 인덱스는 사용불가. 인덱스를 커스터마이징했기때문
scores[0]

KeyError: 0

In [ ]:
# 인덱스가 숫자에서 문자열로 변경
scores['홍길동']

np.int64(85)

#### Series 연산

In [ ]:
# 화면에 출력되고 끝. 결과값을 담을려면 scores = scores +5 실행
scores +5

홍길동     90
이영희     95
김철수    100
박민수     85
dtype: int64

In [20]:
scores / 2

홍길동    42.5
이영희    45.0
김철수    47.5
박민수    40.0
dtype: float64

In [21]:
scores

홍길동    85
이영희    90
김철수    95
박민수    80
dtype: int64

In [22]:
scores.mean()

np.float64(87.5)

In [23]:
scores.max()

np.int64(95)

In [24]:
scores.sum()

np.int64(350)

In [25]:
scores.std()

np.float64(6.454972243679028)

In [26]:
scores.count()

np.int64(4)

- Numpy와 통계함수가 거의 유사하게 존재
- 예전에는 속도문제로 Numpy를 많이 사용했으나, 현재는 사용효율이 높지않아 Pandas 사용으로 충분

#### DataFrame
> Pandas에서 2차원 표형태 데이터를 표현하는 자료 구조
- Pandas의 기본 자료구조형
- Excel, CSV(excel형태 텍스트파일), DB 데이블과 거의 동일한 구조

In [31]:
# DataFrame을 직접 생성할때 사용.
# 파이썬 딕셔너리 사용
raw_data = {
    'name' : ['홍길동','김철수','이영희','박민수','성유고','애슐리'],
    'age' : [20,21,22,23,30,29],
    'major' : ['데이터분석', '웹개발', '인공지능','임베디드','인공지능','웹개발'],
    'score' : [85,90,95,80,90,100]
}
raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
 'age': [20, 21, 22, 23, 30, 29],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 80, 90, 100]}

In [32]:
# 일반적으로 DataFrame을 줄여서 df로 변수명 많이 활용
df = pd.DataFrame(raw_data)

df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   30   인공지능     90
5  애슐리   29    웹개발    100

#### DataFrame 구조 확인
- Numpy 의 shape, size, dtype, ndim과 유사한 기능

In [ ]:
# 앞쪽 5개의 데이터 확인
df.head()

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   30   인공지능     90

In [ ]:
# 기본 5개 > 3개만 확인
df.head(3)

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95

In [ ]:
# 마지막 데이터 확인 (기본5개)
df.tail()

  name  age major  score
1  김철수   21   웹개발     90
2  이영희   22  인공지능     95
3  박민수   23  임베디드     80
4  성유고   30  인공지능     90
5  애슐리   29   웹개발    100

In [37]:
df.tail(2)

  name  age major  score
4  성유고   30  인공지능     90
5  애슐리   29   웹개발    100

In [38]:
# 행과 열의 개수
df.shape

(6, 4)

In [39]:
df.columns

Index(['name', 'age', 'major', 'score'], dtype='str')

In [40]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [41]:
# 컬럼별 타입과 결측값 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   age     6 non-null      int64
 2   major   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

#### 기본 통계
- 수치타입만 나옴

In [42]:
df.describe()

             age       score
count   6.000000    6.000000
mean   24.166667   90.000000
std     4.262237    7.071068
min    20.000000   80.000000
25%    21.250000   86.250000
50%    22.500000   90.000000
75%    27.500000   93.750000
max    30.000000  100.000000

In [43]:
df.age.mean()

np.float64(24.166666666666668)

In [44]:
df['age'].mean()

np.float64(24.166666666666668)

In [45]:
df.age.median()

np.float64(22.5)

In [ ]:
# 25% 값 / 1분위 수 
df.age.quantile(0.25)

np.float64(21.25)

In [ ]:
# 2분위 수. median()과 동일
df.age.quantile(0.5)

np.float64(22.5)