## 판다스 집계

### 집계
> 계산, 통계, 그룹핑으로 원데이터에서 수치적으로 필요한 값을 재가공

In [1]:
import numpy as np
import pandas as pd

In [ ]:
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer": ["홍길동", "김철수", "이영희", "홍길동", "박민수", "김철수"],
    "product_id": ["P001", "P002", "P001", "P003", "P002", "P003"],
    "quantity": [2, 1, 3, 1, 2, 4],
    "unit_price": [30000, 15000, 30000, 8000, 15000, 8000],
    "order_date": [
        "2026-09-01",
        "2026-09-01",
        "2026-09-02",
        "2026-09-02",
        "2026-09-03",
        "2026-09-03"
    ]
})

# 주문번호, 고객명, 상품ID, 수량, 단가, 주문일자로 구성된 데이터
orders

   order_id customer product_id  quantity  unit_price  order_date
0         1      홍길동       P001         2       30000  2026-09-01
1         2      김철수       P002         1       15000  2026-09-01
2         3      이영희       P001         3       30000  2026-09-02
3         4      홍길동       P003         1        8000  2026-09-02
4         5      박민수       P002         2       15000  2026-09-03
5         6      김철수       P003         4        8000  2026-09-03

#### 파생 컬럼 생성

- 단가 * 수량 > 주문금액 컬럼 생성

In [25]:
orders['total_price'] = orders['quantity'] * orders['unit_price']

In [26]:
orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반,VIP,VIP
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN
2,3,이영희,P001,3,30000,2026-09-02,90000,일반,VIP,VIP
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN

#### 조건을 이용한 컬럼 생성

- 조건 연산자 (> , < ,>= , <=)와 논리연산자(&, |, ~) 등을 사용해서 필요한 조건에 맞는 데이터만 필터링
- 필터링 후 파생컬럼 생성

In [6]:
orders['customer_type'] = '일반'

orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반
1,2,김철수,P002,1,15000,2026-09-01,15000,일반
2,3,이영희,P001,3,30000,2026-09-02,90000,일반
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반
4,5,박민수,P002,2,15000,2026-09-03,30000,일반
5,6,김철수,P003,4,8000,2026-09-03,32000,일반

In [17]:
orders['total_price'] > 50000

0     True
1    False
2     True
3    False
4    False
5    False
Name: total_price, dtype: bool

In [22]:
condition = orders['total_price'] >= 50000

In [23]:
orders.loc[condition]

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반,VIP,VIP
2,3,이영희,P001,3,30000,2026-09-02,90000,일반,VIP,VIP

In [24]:
orders.loc[orders['total_price'] >= 50000]

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,일반,VIP,VIP
2,3,이영희,P001,3,30000,2026-09-02,90000,일반,VIP,VIP

In [27]:
orders.loc[orders['total_price'] >= 50000, 'customer_type'] = 'VIP'

In [29]:
orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN

#### apply() 함수 사용
- apply() 함수 내에 사용할 사용자 정의 함수
- 학점 등 여러 구분으로 나눠지는 도메인 값의 컬럼을 생성할때 유용

In [30]:
def get_order_grade(total_price):
    if total_price >= 80000:
        return 'A'
    elif total_price >= 30000:
        return 'B'
    else:
        return 'C'

In [31]:
get_order_grade(85000)

'A'

In [32]:
get_order_grade(25000)

'C'

In [ ]:
# total_price 컬럼의 값을 사용해서 get_order_grade 함수를 적용하여 행별로 grade 컬럼을 생성
orders['grade'] = orders['total_price'].apply(get_order_grade)

In [35]:
orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B

In [36]:
orders.dtypes

order_id          int64
customer            str
product_id          str
quantity          int64
unit_price        int64
order_date          str
total_price       int64
customer_type       str
coustomer_type      str
costomer_type       str
grade               str
dtype: object

In [37]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        6 non-null      int64
 1   customer        6 non-null      str
 2   product_id      6 non-null      str
 3   quantity        6 non-null      int64
 4   unit_price      6 non-null      int64
 5   order_date      6 non-null      str
 6   total_price     6 non-null      int64
 7   customer_type   6 non-null      str
 8   coustomer_type  2 non-null      str
 9   costomer_type   2 non-null      str
 10  grade           6 non-null      str
dtypes: int64(4), str(7)
memory usage: 660.0 bytes

In [40]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [ ]:
# 날짜형식으로 변경하면, 년.월.일 등으로 분리해서 데이터 사용이 가능
orders['order_date'].dt.day

0    1
1    1
2    2
3    2
4    3
5    3
Name: order_date, dtype: int32

#### 정렬
- DB order by 와 동일

In [47]:
orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B

- by : 정렬할 컬럼
- ascending : True 오름차순 , False 내림차순

In [48]:
orders.sort_values(by='total_price', ascending=False)

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C

#### CONCAT
- 데이터 합치기

In [50]:
week1 = pd.DataFrame({
    "order_id": [1, 2],
    "customer": ["홍길동", "김철수"],
    "amount": [60000, 15000]
})
 
week2 = pd.DataFrame({
    "order_id": [3, 4],
    "customer": ["이영희", "박민수"],
    "amount": [90000, 30000]
})

In [51]:
week1

   order_id customer  amount
0         1      홍길동   60000
1         2      김철수   15000

In [52]:
week2

   order_id customer  amount
0         3      이영희   90000
1         4      박민수   30000

In [ ]:
# 이전 인덱스가 그대로 반영
pd.concat([week1, week2])

   order_id customer  amount
0         1      홍길동   60000
1         2      김철수   15000
0         3      이영희   90000
1         4      박민수   30000

In [ ]:
# 일반적으로 가장 많이 사용하는 방법
pd.concat([week1, week2], ignore_index=True)

   order_id customer  amount
0         1      홍길동   60000
1         2      김철수   15000
2         3      이영희   90000
3         4      박민수   30000

#### Merge
- DB Join과 동일

In [57]:
products = pd.DataFrame({
    "product_id": ["P001", "P002", "P003"],
    "product_name": ["키보드", "마우스", "USB"],
    "category": ["주변기기", "주변기기", "저장장치"]
})

In [59]:
orders

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B

In [58]:
products

  product_id product_name category
0       P001          키보드     주변기기
1       P002          마우스     주변기기
2       P003          USB     저장장치

In [63]:
pd.merge(orders, products, on='product_id')

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade,product_name,category
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B,키보드,주변기기
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C,마우스,주변기기
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A,키보드,주변기기
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C,USB,저장장치
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B,마우스,주변기기
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B,USB,저장장치

- how : inner, left, right 가 99% 사용

In [64]:
pd.merge(orders, products, on='product_id', how='left')

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade,product_name,category
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B,키보드,주변기기
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C,마우스,주변기기
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A,키보드,주변기기
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C,USB,저장장치
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B,마우스,주변기기
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B,USB,저장장치

In [67]:
products.loc[3] = ['P004', '모니터', '디스플레이']

In [ ]:
products

  product_id product_name category
0       P001          키보드     주변기기
1       P002          마우스     주변기기
2       P003          USB     저장장치
3       P004          모니터    디스플레이

In [71]:
pd.merge(orders, products, on='product_id', how='left')

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade,product_name,category
0,1,홍길동,P001,2,30000,2026-09-01,60000,VIP,VIP,VIP,B,키보드,주변기기
1,2,김철수,P002,1,15000,2026-09-01,15000,일반,NaN,NaN,C,마우스,주변기기
2,3,이영희,P001,3,30000,2026-09-02,90000,VIP,VIP,VIP,A,키보드,주변기기
3,4,홍길동,P003,1,8000,2026-09-02,8000,일반,NaN,NaN,C,USB,저장장치
4,5,박민수,P002,2,15000,2026-09-03,30000,일반,NaN,NaN,B,마우스,주변기기
5,6,김철수,P003,4,8000,2026-09-03,32000,일반,NaN,NaN,B,USB,저장장치

In [72]:
pd.merge(orders, products, on='product_id', how='right')

,order_id,customer,product_id,quantity,unit_price,order_date,total_price,customer_type,coustomer_type,costomer_type,grade,product_name,category
0,1.0,홍길동,P001,2.0,30000.0,2026-09-01,60000.0,VIP,VIP,VIP,B,키보드,주변기기
1,3.0,이영희,P001,3.0,30000.0,2026-09-02,90000.0,VIP,VIP,VIP,A,키보드,주변기기
2,2.0,김철수,P002,1.0,15000.0,2026-09-01,15000.0,일반,NaN,NaN,C,마우스,주변기기
3,5.0,박민수,P002,2.0,15000.0,2026-09-03,30000.0,일반,NaN,NaN,B,마우스,주변기기
4,4.0,홍길동,P003,1.0,8000.0,2026-09-02,8000.0,일반,NaN,NaN,C,USB,저장장치
5,6.0,김철수,P003,4.0,8000.0,2026-09-03,32000.0,일반,NaN,NaN,B,USB,저장장치
6,NaN,NaN,P004,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,모니터,디스플레이

#### group by 집계
- DB group by 동일

In [76]:
orders.groupby('customer')

In [77]:
orders.groupby('customer')['total_price'].sum()

customer
김철수    47000
박민수    30000
이영희    90000
홍길동    68000
Name: total_price, dtype: int64

In [78]:
# 데이터프레임으로 변환
orders.groupby('customer')['total_price'].sum().reset_index()

  customer  total_price
0      김철수        47000
1      박민수        30000
2      이영희        90000
3      홍길동        68000

#### 여러 통계를 한번에 계산

In [ ]:
# 고객별로 기본통계
orders.groupby('customer')['total_price'].agg(
    ['count', 'sum', 'mean', 'max', 'min','std']
)

          count    sum     mean    max    min           std
customer
김철수           2  47000  23500.0  32000  15000  12020.815280
박민수           1  30000  30000.0  30000  30000           NaN
이영희           1  90000  90000.0  90000  90000           NaN
홍길동           2  68000  34000.0  60000   8000  36769.552622

In [ ]:
# 통계치 csv 파일로 저장
orders.groupby('customer')['total_price'].agg(
    ['count', 'sum', 'mean', 'max', 'min','std']
).to_csv('../data/고객별구매통계.csv', encoding='utf-8')